FROM jenkins/jenkins:lts

USER root

# Install dependencies
RUN apt-get update && \
    apt-get install -y \
    curl \
    unzip \
    ca-certificates \
    gnupg \
    lsb-release \
    apt-transport-https \
    software-properties-common

# Install AWS CLI v2
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -rf awscliv2.zip aws

# Install Docker
RUN apt-get install -y docker.io

# Add jenkins user to docker group
RUN usermod -aG docker jenkins

# Install kubectl (latest stable)
# Install kubectl from Amazon EKS (specific version)
RUN curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/kubectl && \
    chmod +x ./kubectl && \
    mv ./kubectl /usr/local/bin/kubectl && \
    kubectl version --short --client


USER jenkins

-------
deployment and service file

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-server
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: chaitanyabaki/new:jenkinsaws_v1  # Replace with your Docker Hub image
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
  - protocol: TCP
    port: 80        # Port exposed by LoadBalancer
    targetPort: 8080  # Port on the container
